### ISSUE TITLE
Where is vue-index.php file?

### ISSUE THREAD

**Issue by Djules** [jmheretik/kirby-vue-starterkit#23]
First of all, thank you so much for this work!
I'm working on a Nuxt SPA with Kirby as headless CMS, and this starter kit is EXACTLY what I'm looking for! 👍 

I'm trying to inject the Vue app into Kirby, using `useVueIndex`option, but I don't see any `vue-index.php` file into the Kirby plugin, am I looking wrong? 🤔

**Comment by jmheretik** [comment]
hey, im glad you like this project. have you also ticked `inject` to `true` in kirby.config? oh and of course you need to build (`npm run build`) the app each time to regenerate the `vue-index.php` file.

**Comment by Djules** [comment]
Hi, thanks for your reply!

I did set `inject` option to `true`, but I missed the fact that `vue-index.php` file was generated by Nuxt build task. 🤭
To be truly honest with you, I haven't even tried to run this task yet… 😬

Soooo I can see it now, thank you!
